services:

  mariadb:
    image: mariadb:lts
    container_name: cappa_mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - cappadata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: cappa_pma
    restart: always
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8005:80

  mailer:
    image: schickling/mailcatcher
    container_name: cappa_mailcatcher
    ports: ["1025:1025","1080:1080"]


volumes:
  cappadata:
